CREATE TABLE users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  balance integer,
  created_at timestamp,
  updated_at timestamp
);


CREATE TABLE products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar,
  price varchar,
  created_at timestamp,
  updated_at timestamp
);


CREATE TABLE purchases (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  product_id integer REFERENCES products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  created_at timestamp
);

INSERT INTO users (name, balance, created_at, updated_at)
VALUES ('user1', 1000, NOW(), NOW());

INSERT INTO products (name, price, created_at, updated_at)
VALUES ('ak47', 99, NOW(), NOW());